#!/bin/bash

############################################################
# Creating all-site vcf                                    #
############################################################

# Two steps
# 1. Calling all-site vcf by bcftools and filter by vcftools
# 2. Merge all-site vcf with vcf generated by deepvariant

bamfolder=""
assembly=""
vcf="" #vcf.gz file
output=""

## Call all-site variants
ls ${bamfolder}/*.bam > bamlist.txt
bcftools mpileup \
  -a DP \
  -f ${assembly} \
  -b bamlist.txt | \
  bcftools call \
  -m -Oz -f GQ \
  -o allsite.unfiltered.vcf.gz

## Filter
vcftools \
  --gzvcf allsite.unfiltered.vcf.gz \
  --remove-indels \
  --max-missing 0.8 \
  --min-meanDP 15 \
  --max-meanDP 50 \
  --minDP 10 \
  --maxDP 100 \
  --recode \
  --stdout | \
  bgzip -c > allsite.filtered.vcf.gz

## Extract non-variant sites
bcftools \
  view -C0 \
  allsite.filtered.vcf.gz | \
  bgzip -c \
    > allsite.filtered.nonvariant.vcf.gz

tabix allsite.filtered.nonvariant.vcf.gz
tabix ${vcf}

## Remove non-variant sites that overlap with deepvariant vcf

bedtools \
  intersect \
  -a allsite.filtered.nonvariant.vcf.gz \
  -b ${vcf} -v > \
  allsite.filtered.nonvariant.nonoverlapping.noheader.vcf

bcftools \
  view -h \
  allsite.filtered.nonvariant.vcf.gz > header.txt

cat \
  header.txt allsite.filtered.nonvariant.nonoverlapping.noheader.vcf > \
  allsite.filtered.nonvariant.nonoverlapping.vcf

## Merge two vcf files

gatk \
  MergeVcfs \
  -I allsite.filtered.nonvariant.nonoverlapping.vcf \
  -I ${vcf} \
  -R ${assembly} \
  -O combined.allsite.vcf

bgzip -c combined.allsite.vcf> ${output}
tabix ${output}
